# data parameters
dataset_name: mouse-cable
data_with_subfolder: False
train_data_path: /Users/wgillis/Desktop/inpaint-training
val_data_path:
resume:
batch_size: 48
image_shape: [80, 80, 3]
mask_shape: [30, 30]
mask_batch_same: True
max_delta_shape: [10, 10]
margin: [0, 0]
discounted_mask: True
spatial_discounting_gamma: 0.9
random_crop: True
mask_type: hole     # hole | mosaic
mosaic_unit_size: 12

# training parameters
expname: benchmark
cuda: False
gpu_ids: [0]  # set the GPU ids to use, e.g. [0] or [1, 2]
num_workers: 6
lr: 0.0001
beta1: 0.5
beta2: 0.9
niter: 500000
print_iter: 10
viz_iter: 50
viz_max_out: 16
snapshot_save_iter: 50

# loss weight
coarse_l1_alpha: 1.2
l1_loss_alpha: 1.2
ae_loss_alpha: 1.2
global_wgan_loss_alpha: 1.
gan_loss_alpha: 0.001
wgan_gp_lambda: 10

# network parameters
netG:
  input_dim: 5
  ngf: 32

netD:
  input_dim: 3
  ndf: 64
